FROM openjdk:17

WORKDIR /app

COPY target/Course-Recommendation-spring-boot.jar /app/Course-Recommendation-spring-boot.jar

EXPOSE 8080

CMD ["java", "-jar", "Course-Recommendation-spring-boot.jar"]
